name: Maintenance

permissions:
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          stale-issue-message: 'This issue has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          close-issue-message: 'This issue has now been closed. Please raise a new Issue instead of re-opening existing ones, unless you believe this was closed by accident.'
          days-before-issue-stale: 31
          days-before-issue-close: 7
          stale-issue-label: 'stale'
          only-issue-labels: 'awaiting-feedback'
          exempt-issue-labels: 'confirmed'

          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          close-pr-message: 'This pull request has now been closed. If you want to continue working on it or you believe it has been closed by accident, feel free to re-open it.'
          days-before-pr-stale: 31
          days-before-pr-close: 7
          stale-pr-label: 'stale'
          exempt-pr-labels: 'work-in-progress,dependencies'
          exempt-draft-pr: true
